apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - resource-quota.yaml
  - configmap.yaml
  - secret.example.yaml
  - vllm-server.yaml
  - api.yaml
  - prometheus.yaml
