apiVersion: v1
kind: ResourceQuota
metadata:
  name: vllm-quota
  namespace: vllm
spec:
  hard:
    requests.cpu: "8"
    requests.memory: 24Gi
    limits.cpu: "16"
    limits.memory: 48Gi
    requests.nvidia.com/gpu: "1"
    limits.nvidia.com/gpu: "1"
    pods: "8"
